// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcTL80y5K6FpV5AmYdinSVtisEXQcQ8Tg',
    appId: '1:648629070631:web:aae66265f69f3cf10c5702',
    messagingSenderId: '648629070631',
    projectId: 'mobilemend-aa9c3',
    authDomain: 'mobilemend-aa9c3.firebaseapp.com',
    storageBucket: 'mobilemend-aa9c3.firebasestorage.app',
    measurementId: 'G-HCW2DMYZFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz2f1uIN7zESNIlud1H0c71rLebxsGes8',
    appId: '1:648629070631:android:3d36da658841b72a0c5702',
    messagingSenderId: '648629070631',
    projectId: 'mobilemend-aa9c3',
    storageBucket: 'mobilemend-aa9c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx0SsO-UlBy5cn28Mt6_8FM4D9jspHebk',
    appId: '1:648629070631:ios:c209f17e1d162da10c5702',
    messagingSenderId: '648629070631',
    projectId: 'mobilemend-aa9c3',
    storageBucket: 'mobilemend-aa9c3.firebasestorage.app',
    iosBundleId: 'com.example.mobileServies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx0SsO-UlBy5cn28Mt6_8FM4D9jspHebk',
    appId: '1:648629070631:ios:c209f17e1d162da10c5702',
    messagingSenderId: '648629070631',
    projectId: 'mobilemend-aa9c3',
    storageBucket: 'mobilemend-aa9c3.firebasestorage.app',
    iosBundleId: 'com.example.mobileServies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcTL80y5K6FpV5AmYdinSVtisEXQcQ8Tg',
    appId: '1:648629070631:web:e26a9adfe38f9f280c5702',
    messagingSenderId: '648629070631',
    projectId: 'mobilemend-aa9c3',
    authDomain: 'mobilemend-aa9c3.firebaseapp.com',
    storageBucket: 'mobilemend-aa9c3.firebasestorage.app',
    measurementId: 'G-1CEGC8B4Y2',
  );
}
